feat: move openai to its own platform

diff --git a/gpt b/gpt
--- a/gpt
+++ b/gpt
@@ -80,13 +80,7 @@ bootstrap() {
     CLIGPT_CONTEXT_STORAGE="."
   fi
   if test -z "$CLIGPT_TIMEOUT"; then
-    timeout=30
-  fi
-  if test -z "$CLIGPT_TEMP"; then
-    temp=""
-  fi
-  if test -z "$CLIGPT_TOKEN"; then
-    token=""
+    CLIGPT_TIMEOUT=30
   fi
 
   load_platforms
@@ -114,7 +108,7 @@ usage() {
     first_line='      \(.value.description)\n'
     second_line='        Default API base URL : \(.value.base // "None specified") (can be set through CLIGPT_\(.value.key)_API_BASE)'
     third_line='        Default model        : \(.value.model // "None specified") (can be set through CLIGPT_\(.value.key)_MODEL)'
-    echo "$platforms" | jq -rS "to_entries | map(\"  - \(.key)\n$first_line$second_line\n$third_line\") | join(\"\n\")"
+    parsejson "$platforms" -S "to_entries | map(\"  - \(.key)\n$first_line$second_line\n$third_line\") | join(\"\n\")"
     echo
     echo "  By default, each platform will be tested for a valid setup and get selected. Any platform required a remote call will not be tested and will be selected as a fallback."
   fi
@@ -136,11 +130,11 @@ usage() {
   echo "FLAGS"
   echo "  -h, --help                       Show this message"
   echo "  -p, --platform=<name>            LLM platform to use (see PLATFORMS above for more details)"
-  echo "  -m, --model=<name>               ID of the model to use (default to $(fallback_default "$model"))"
-  echo "  -T, --temperature=<temp>         Sampling temperature, higher is more random (default to $(fallback_default "$temp"))"
-  echo "  -t, --max-tokens=<number>        Maximum number of tokens to generate in the completion (default to $(fallback_default "$token"))"
+  echo "  -m, --model=<name>               ID of the model to use (default to $(fallback_default "$CLIGPT_MODEL"))"
+  echo "  -T, --temperature=<temp>         Sampling temperature, higher is more random (default to $(fallback_default "$CLIGPT_TEMP"))"
+  echo "  -t, --max-tokens=<number>        Maximum number of tokens to generate in the completion (default to $(fallback_default "$CLIGPT_TOKEN"))"
   echo "  -c, --context, --context=<file>  Use chat context (default to false), optionally use and store the context in the given file. The prompt from command line will be passed as a system message to the assistant, cannot be used in a pipe"
-  echo "  --timeout=<number>               Maximum number of seconds before request timed out (default to "$(fallback_default "$timeout")")"
+  echo "  --timeout=<number>               Maximum number of seconds before request timed out (default to "$(fallback_default "$CLIGPT_TIMEOUT")")"
   echo "  --fancy[=<number>]               Use fancy UI with the given minimum padding (default to "$padding")"
   echo "  --platforms                      List all available platforms (will start download supported platforms if no platform found)"
   echo "  --models                         List all available models"
@@ -223,7 +217,7 @@ handle_gpt_response() {
   errmsg="$(printf '%s' "$response" | jq -er '.error.message')"
   if test "$?" -eq 0; then
     restore_ui
-    printf 'ERROR: [%s] %s\n' "$(printf '%s' "$response" | jq -r '.error.type')" "$errmsg" >&2
+    printf 'ERROR: [%s] %s\n' "$(parsejson "$response" '.error.type')" "$errmsg" >&2
     return 1
   fi
   return 0
@@ -266,14 +260,14 @@ run_task() {
 load_platforms() {
   platforms="{}"
   for platform_path in "$CLIGPT_PLATFORM_STORAGE"/*.sh; do
-    platform_name="$(basename "$platform_path")"
+    local platform_name="$(basename "$platform_path")"
     if test "$platform_name" = '*.sh'; then
       break
     fi
 
     . "$platform_path"
-    platform_data="$(platform_info)"
-    platforms="$(setitem "$platforms" "$(echo "$platform_data" | jq -r '.fn')" "$platform_data")"
+    local platform_data="$(platform_info)"
+    platforms="$(setitem "$platforms" "$(parsejson "$platform_data" '.fn')" "$platform_data")"
   done
 }
 
@@ -284,6 +278,7 @@ download_platforms() {
 
   echo "Fetching platforms..." >&2
   # TODO
+  # curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/spywhere/gpt/contents/ | jq 'map({ (.name|tostring): . }) | add'
 
   load_platforms
 
@@ -298,79 +293,33 @@ validate_platform() {
     return 2
   fi
 
-  if test -n "$model"; then
-    CLIGPT_MODEL="$model"
-  fi
-
-  if test -z "$platform"; then
-    platform="$CLIGPT_PLATFORM"
-  fi
-  has_test=0
-  if test -z "$platform"; then
-    for platform_name in $(echo "$platforms" | jq -r 'keys[]'); do
+  local has_test=0
+  if test -z "$CLIGPT_PLATFORM"; then
+    for platform_name in $(parsejson "$platforms" 'keys[]'); do
       if "$platform_name" test; then
-        platform="$platform_name"
+        CLIGPT_PLATFORM="$platform_name"
         has_test=1
-        echo "No platform specified, using '$platform' instead" >&2
+        echo "No platform specified, using '$CLIGPT_PLATFORM' instead" >&2
         break
       fi
     done
   fi
 
-  if test -z "$platform"; then
+  if test -z "$CLIGPT_PLATFORM"; then
     echo "ERROR: no valid platform found" >&2
     return 1
   fi
 
-  platform_data="$(echo "$platforms" | jq -r ".[\"$platform\"].fn // \"\"")"
+  local platform_data="$(parsejson "$platforms" ".[\"$CLIGPT_PLATFORM\"].fn // \"\"")"
   if test $? -ne 0 -o -z "$platform_data"; then
-    echo "ERROR: platform '$platform' is not a valid platform" >&2
+    echo "ERROR: platform '$CLIGPT_PLATFORM' is not a valid platform" >&2
     return 1
   fi
 
-  if test "$has_test" -eq 0 && ! "$platform" test; then
+  if test "$has_test" -eq 0 && ! "$CLIGPT_PLATFORM" test; then
+    echo "ERROR: platform '$CLIGPT_PLATFORM' is not a valid platform (failed the test)" >&2
     return 3
   fi
-}
-
-openai() {
-  local path="$1"
-  local body="$2"
-  local filter="$3"
-  local method="POST"
-  if test -z "$3"; then
-    body=""
-    filter="$2"
-    method="GET"
-  elif test "$debug" -ge 1; then
-    printf 'Req[%s]: %s\n' "$path" "$body" >&2
-  fi
-  if test "$debug" -eq 2; then
-    return 4
-  fi
-  task() {
-    curl -m "$timeout" -X "$method" -d "$body" -sSL "$OPENAI_API_BASE/$path" -H 'Content-Type: application/json' -H "Authorization: Bearer $OPENAI_API_KEY" 2>/dev/null
-  }
-  local response
-  response="$(run_task task)"
-  if test $? -ne 0; then
-    return 1
-  fi
-
-  if test "$debug" -ge 1; then
-    printf 'Res[%s]: %s\n' "$path" "$response" >&2
-  fi
-
-  printf '%s' "$response" | jq '.' >/dev/null 2>&1
-  if test $? -ne 0; then
-    return 2
-  fi
-
-  if ! handle_gpt_response "$response"; then
-    return 3
-  fi
-
-  printf '%s' "$response" | jq -r "$filter"
 }
 
 handle_status() {
@@ -396,6 +345,12 @@ handle_status() {
   return "$status"
 }
 
+parsejson() {
+  local value="$1"
+  shift
+  printf '%s' "$value" | jq -r "$@"
+}
+
 tojson() {
   printf '%s' "$*" | jq -sRr 'tojson'
 }
@@ -412,15 +367,16 @@ list_platforms() {
   download_platforms
 
   echo "Available platforms:"
-  echo "$platforms" | jq -r 'keys[] | "  - \(.)"'
+  parsejson "$platforms" 'keys[] | "  - \(.)"'
 }
 
 models() {
   echo "Available models:"
-  openai models '.data[] | "  - \(.id)\n      by: \(.owned_by)"'
+  local models="$("$CLIGPT_PLATFORM" models)"
   if ! handle_status "$?"; then
     exit 1
   fi
+  parsejson "$models" '.[] | "  - \(.id)\n      by: \(.by)"'
 }
 
 validate_context() {
@@ -519,35 +475,35 @@ main() {
           echo "ERROR: a number of seconds is required (perhaps missing an equal sign?)" >&2
           return 1
         fi
-        timeout="$value"
+        CLIGPT_TIMEOUT="$value"
         ;;
       -T | --temperature)
         if test -z "$equal_sign"; then
           echo "ERROR: a temperature is required (perhaps missing an equal sign?)" >&2
           return 1
         fi
-        temp="$value"
+        CLIGPT_TEMP="$value"
         ;;
       -t | --max-tokens)
         if test -z "$equal_sign"; then
           echo "ERROR: a number of tokens is required (perhaps missing an equal sign?)" >&2
           return 1
         fi
-        token="$value"
+        CLIGPT_TOKEN="$value"
         ;;
       -p | --platform)
         if test -z "$equal_sign"; then
           echo "ERROR: a platform is required (perhaps missing an equal sign?)" >&2
           return 1
         fi
-        platform="$value"
+        CLIGPT_PLATFORM="$value"
         ;;
       -m | --model)
         if test -z "$equal_sign"; then
           echo "ERROR: a model ID is required (perhaps missing an equal sign?)" >&2
           return 1
         fi
-        model="$value"
+        CLIGPT_MODEL="$value"
         ;;
       -c | --context)
         if test -z "$equal_sign"; then
@@ -635,18 +591,6 @@ main() {
     return
   fi
 
-  local body="{}"
-
-  if test -n "$model"; then
-    body="$(setitem "$body" "model" "$(tojson "$model")")"
-  fi
-  if test -n "$token"; then
-    body="$(setitem "$body" "max_tokens" "$token")"
-  fi
-  if test -n "$temp"; then
-    body="$(setitem "$body" "temperature" "$temp")"
-  fi
-
   local prompts="[]"
   if test -n "$context"; then
     if test "$context" != '-'; then
@@ -663,7 +607,7 @@ main() {
         return 1
       fi
     elif test -n "$prompt"; then
-      data="$(printf '{"role":"system","content":%s}' "$(tojson "$prompt")")"
+      local data="$(printf '{"role":"system","content":%s}' "$(tojson "$prompt")")"
       printf '%s[System]%s %s\n' "$esc_blue" "$esc_reset" "$prompt"
       prompts="$(additem "$prompts" "$data")"
     fi
@@ -692,15 +636,13 @@ main() {
     fi
 
     draw_ui
-    body="$(setitem "$body" "messages" "$prompts")"
-    response="$(openai chat/completions "$body" '.')"
+    response="$("$CLIGPT_PLATFORM" chat/completions "$prompts")"
     if ! handle_status "$?"; then
       return 1
     fi
     restore_ui
-    content="$(printf '%s' "$response" | jq -r '.choices[] | .message.content')"
-    data="$(printf '{"role":"assistant","content":%s}' "$(tojson "$content")")"
-    prompts="$(additem "$prompts" "$data")"
+    local content="$(parsejson "$response" '.content')"
+    prompts="$(additem "$prompts" "$response")"
     if test -n "$context"; then
       printf '%s[Assistant]%s %s\n' "$esc_yellow" "$esc_reset" "$content"
     else
