feat: add attachment validation

diff --git a/gpt b/gpt
--- a/gpt
+++ b/gpt
@@ -138,6 +138,7 @@ usage() {
   echo "  -h, --help                       Show this message"
   echo "  -p, --platform=<name>            LLM platform to use (see PLATFORMS above for more details)"
   echo "  -m, --model=<name>               ID of the model to use (default to $(fallback_default "$CLIGPT_MODEL"))"
+  echo "  -f, --file=<file>                File to be attached along with a prompt"
   echo "  -T, --temperature=<temp>         Sampling temperature, higher is more random (default to $(fallback_default "$CLIGPT_TEMP"))"
   echo "  -t, --max-tokens=<number>        Maximum number of tokens to generate in the completion (default to $(fallback_default "$CLIGPT_TOKEN"))"
   echo "  -c, --context, --context=<file>  Use chat context (default to false), optionally use and store the context in the given file. The prompt from command line will be passed as a system message to the assistant, cannot be used in a pipe"
@@ -195,19 +196,31 @@ copilot_examples() {
   local command='find -name "*.ts" | grep -v node_modules'
   local additional
   additional="$("$CLIGPT_PLATFORM" messages user "$command")"
+  if test $? -ne 0; then
+    return 1
+  fi
   prompts="$(additems "$prompts" "$additional")"
   # shellcheck disable=SC2016
   result="$(printf -- '--- Command ---\n\n%s\n\n--- Explanation ---\n\n- %s\n  - %s\n- %s\n  - %s' "$command" '`find` is used to list files.' '`-name "*.ts"` stipulates that we search for files ending in `.ts`.' '`| grep` means we pass that list of files to `grep` which filters the list.' '`-v node_modules` means we exclude all files containing node_modules in its path.')"
   additional="$("$CLIGPT_PLATFORM" messages assistant "$result")"
+  if test $? -ne 0; then
+    return 1
+  fi
   prompts="$(additems "$prompts" "$additional")"
 
   # shellcheck disable=SC2016
   command="$(printf '%s\n  %s\n  %s\n%s' 'for file in $(find -name "*.py"); do' 'echo "$file";' 'wc -l $file;' 'done')"
   additional="$("$CLIGPT_PLATFORM" messages user "$command")"
+  if test $? -ne 0; then
+    return 1
+  fi
   prompts="$(additems "$prompts" "$additional")"
   # shellcheck disable=SC2016
   result="$(printf -- '--- Command ---\n\n%s\n\n--- Explanation ---\n\n- %s\n  - %s\n    - %s\n- %s\n  - %s\n  - %s\n    - %s' "$command" 'The for loop iterates over a list of items and executes its body for each, using the loop variable `$file`.' 'The list of items is the output of a sub-call to `find` which is used to list files.' '`-name "*.py"` stipulates that we search for files ending in `.py`.' 'The loop body executes two commands for each file:' '`echo "$file"` will print the name of the current file to the terminal.' '`wc` is used to count the number of lines in the current file.' '`-l` specifies that we only want the line count, not the word or character count.')"
   additional="$("$CLIGPT_PLATFORM" messages assistant "$result")"
+  if test $? -ne 0; then
+    return 1
+  fi
   prompts="$(additems "$prompts" "$additional")"
 
   printf '%s' "$prompts"
@@ -550,7 +563,7 @@ command_help() {
   echo '  `, """                             Prefix the prompt with a backtick or triple quotes for multi-line prompt'
   echo '  /help, /h, /?                      Print this help message'
   echo '  /clear, /forget                    Clear the conversation'
-  echo '  /upload <file>, /attach <file>     Attach a file along with the next prompt'
+  echo '  /upload [file], /attach [file]     Clear all attachments or add an attachment along with the next prompt'
   echo '  /system <prompt>                   Insert system prompt into the conversation'
   echo '  /regenerate, /regen                Regenerate the last response'
   echo '  /undo                              Remove the last prompt and response'
@@ -653,6 +666,18 @@ main() {
           return 1
         fi
         CLIGPT_TIMEOUT="$value"
+        ;;
+      -f | --file)
+        if test -z "$equal_sign"; then
+          echo "ERROR: a file is required (perhaps missing an equal sign?)" >&2
+          return 1
+        fi
+        if test -f "$value"; then
+          CLIGPT_FILE="$value"
+        else
+          echo "ERROR: file '$value' is not exists" >&2
+          return 1
+        fi
         ;;
       -T | --temperature)
         if test -z "$equal_sign"; then
@@ -784,7 +809,11 @@ main() {
         return 1
       fi
     elif test -n "$prompt"; then
-      local data="$("$CLIGPT_PLATFORM" messages system "$prompt")"
+      local data
+      data="$("$CLIGPT_PLATFORM" messages system "$prompt")"
+      if test $? -ne 0; then
+        return 1
+      fi
       prompts="$(additems "$prompts" "$data")"
       printf '%s[System]%s %s\n' "$esc_blue" "$esc_reset" "$prompt"
     fi
@@ -840,10 +869,11 @@ main() {
                 esac
 
                 if test -z "$value"; then
-                  echo "ERROR: a file is required" >&2
+                  echo "All attachment cleared" >&2
+                  CLIGPT_FILE=""
                 elif test -f "$value"; then
                   echo "File '$value' will be attached with the next prompt" >&2
-                  # TODO: Attach a file
+                  CLIGPT_FILE="$value"
                 else
                   echo "ERROR: file '$value' is not exists" >&2
                 fi
@@ -924,6 +954,9 @@ main() {
           printf '%s[User]%s %s\n' "$esc_green" "$esc_reset" "$line"
         fi
         current_items="$("$CLIGPT_PLATFORM" messages user "$line")"
+        if test $? -ne 0; then
+          continue
+        fi
       else
         printf '\n'
         restore_ui
@@ -931,11 +964,21 @@ main() {
       fi
     else
       if test -n "$kind"; then
-        local prefix="$("$CLIGPT_PLATFORM" messages system "$(prompt_prefix "$kind")")"
+        local prefix
+        prefix="$("$CLIGPT_PLATFORM" messages system "$(prompt_prefix "$kind")")"
+        if test $? -ne 0; then
+          continue
+        fi
         prompts="$(additem "$prompts" "$prefix")"
         prompts="$(additional_prompts "$kind" "$prompts")"
+        if test $? -ne 0; then
+          continue
+        fi
       fi
       current_items="$("$CLIGPT_PLATFORM" messages user "$prompt")"
+      if test $? -ne 0; then
+        continue
+      fi
     fi
 
     if test "$skip" -eq 0 -a -n "$current_items"; then
@@ -955,6 +998,8 @@ main() {
     else
       printf '%s\n' "$content"
     fi
+    # clear attachments
+    CLIGPT_FILE=""
 
     if test -z "$context"; then
       break
