feat: auto download support platforms

diff --git a/gpt b/gpt
--- a/gpt
+++ b/gpt
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+CLIGPT_PLATFORM_REPO="spywhere/gpt"
+CLIGPT_PLATFORM_PATH="platforms"
+
 tempfile="$(mktemp)"
 cmd_name="$(basename "$0")"
 debug=0
@@ -277,8 +280,23 @@ download_platforms() {
   fi
 
   echo "Fetching platforms..." >&2
-  # TODO
-  # curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/spywhere/gpt/contents/ | jq 'map({ (.name|tostring): . }) | add'
+  platform_files="$(curl -sSL -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/$CLIGPT_PLATFORM_REPO/contents/$CLIGPT_PLATFORM_PATH" | jq 'map({ (.name|tostring): . }) | add')"
+  if test "$?" -ne 0; then
+    echo "ERROR: failed to fetch a list of platforms" >&2
+    return 1
+  fi
+  for platform_file in $(parsejson "$platform_files" 'keys[]'); do
+    local platform_data="$(parsejson "$platform_files" ".[\"$platform_file\"]")"
+    local platform_url="$(parsejson "$platform_data" '.download_url')"
+    printf "Downloading platform '%s' into '$CLIGPT_PLATFORM_STORAGE/$platform_file'..." "$platform_file" >&2
+    curl -sSL "$platform_url" -o "$CLIGPT_PLATFORM_STORAGE/$platform_file" 1>/dev/null 2>&1
+    if test "$?" -ne 0; then
+      printf ' failed\n' >&2
+      echo "ERROR: failed to download platform '$platform_file'" >&2
+      return 1
+    fi
+    printf ' done\n' >&2
+  done
 
   load_platforms
 
